name: Python Cache Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.cache/pip
          key: cache-3ed78d1
          restore-keys: |
            cache-3ed78d1

      - name: Prime cache - prime-cache-3ed78d1
        run: |
          if [ -d ~/.cache/pip ]; then
            echo "Cache exists"
          else
            echo "Cache miss"
          fi

      - name: Install dependencies
        run: pip install -r requirements.txt

